### ISSUE TITLE
Kodi Plugin not working with new version of Jellyfin

### ISSUE THREAD

**Issue by martinjh99** [jellyfin/jellyfin-kodi#152]
**Describe the bug**
Kodi plugin doesn't seem to be logging into the latest version of the docker container.

**To Reproduce**

1. Update Docker container to the latest version
2. Run Kodi with plugin 0.3.6
3. Player won't play anything from jellyfin with Item's failed to play error

**Expected behavior**
Kodi will play the files.

**Logs**
https://pastebin.com/cV3bcB1X

**Screenshots**

**System (please complete the following information):**
 - OS: Windows
 - Jellyfin Version: 10.4.2
 - Addon Version: 0.3.6
 - Kodi 18.4

Only started happening when I upgraded to 10.4.2 - Can play from web
Also thumbnails not showing in Kodi but that might be related to the fact I can't login

**Comment by TrueTechy** [comment]
Hi there,

Using Docker myself and I've just upgraded my jellyfin server to test and using Kodi 18.4 and addon version 0.3.6. No problems with connecting to, logging in to or playing back content with the addon.

Could you provide us with your kodi log file to help us better understand what's going on with your setup?

**Comment by martinjh99** [comment]
Logs are in the Pastebin in the post - https://pastebin.com/cV3bcB1X

**Comment by TrueTechy** [comment]
> Logs are in the Pastebin in the post - https://pastebin.com/cV3bcB1X

Apologies, completely missed that. Been a long week

**Comment by martinjh99** [comment]
:) No worries - It's a problem with auth.server I think looking at the logs myself.

**Comment by aoc** [comment]
@martinjh99 this might be related to https://github.com/jellyfin/jellyfin-kodi/issues/146

I had to manually add the server using the base url. e.g. 192.168.0.100:8096/jellyfin

**Comment by mcarlton00** [comment]
The `auth.server` error is likely a non-issue.  It's a result of some poor function design we inherited and a bit overzealous logging that we haven't had time to work through yet.

aoc is correct that it's probably a baseurl issue.  What you have entered as the server address in Kodi should match what is in your URL bar when accessing the web UI.  ie: if your URL bar shows `http://192.168.0.10:8096/jellyfin/web/index.html#!/home.html`, then Kodi requires `192.168.0.10:8096/jellyfin`.  This was a required change implemented in 10.4.1 of the server, and can be reverted by manually changing the baseurl in the server to `/` instead of `/jellyfin`.  More info can be found in the [release notes](https://github.com/jellyfin/jellyfin/releases/tag/v10.4.1)

**Comment by martinjh99** [comment]
Reading the release notes and trying to change the base url as it says there I can't save the networking settings as it says I need a certificate.  As this is an internal only server I don't need one so where do I disable https ?
