### ISSUE TITLE
 Failed due to an invalid structure

### ISSUE THREAD

**Issue by foncubierta** [jellyfin/jellyfin-kodi#178]
When trying to install the addons on Kodi v18.4, this error indicates to me:
 Failed due to an invalid structure
Can it be solved in any way? Thank you.

**Comment by JustAMan** [comment]
This seems to be an issue with our Kodi plugin, so I've transferred the issue to its repo.

**Comment by oddstr13** [comment]
Could you please provide more details?
How are you installing?
On what device/OS?
Could you please provide Kodi logs?

**Comment by TrueTechy** [comment]
Closing due to no response from reporter

**Comment by gravyboot** [comment]
Having this issue installing on Steam Link using these instructions: https://jellyfin.org/docs/general/clients/kodi.html

the Kodi log says:

"Failed to install Add-on from zip file
Installing the Add-on from zip file located at 
https://kodi.jellyfin.org/repository.jellyfin.kodi.zip failed due to an invalid structure."
