### ISSUE TITLE
Sync doesn't stay enabled - FireTV

### ISSUE THREAD

**Issue by spoolr** [jellyfin/jellyfin-kodi#185]
I haven't quite figured out the frequency, but the Sync Queue won't stay enabled.  I can turn it on, and it's fine for a day or so, but eventually launching Kodi 18.5 will give me the JellyFin for Kodi 0.4 box asking to enable Sync.

Even when I turned the Sync Queue on, the content doesn't update so well.  I was seeing some new things occasionally , so I assumed it was working, but upon checking JellyFin AndroidTV 10.2 there was a lot of content not showing up.

I found an Update Library command to manually update but all the files are updated, not just the new ones.  What should just be a few seconds for a handful of TV shows turns into a 25 minute scan.  Is there a better work around?  

I have turned debug logs on, but I have no idea how to get them off the FireTV.

**Comment by mcarlton00** [comment]
While they integrate pretty tightly together, this repo is strictly for the Kodi addon itself.  The server plugin is over [here](https://github.com/jellyfin/jellyfin-plugin-kodisyncqueue).  If new media is added to your sever while kodi is running, it should automatically be imported regardless of whether the sync queue plugin is running or not.  The Sync Queue plugin really only comes into effect when media was added to the server while kodi was turned off.  When Kodi is started again, it asks the sync queue plugin for what updates have happened.  So if you're having issues with the Sync Queue, that's why you're not seeing good results with the updates.  Make sure you're on the latest version of both Jellyfin and the Kodi Sync Queue plugin, because there was an issue fixed with it a few weeks ago related to not properly providing updates to kodi.

There really isn't anything that can be done on the Kodi side, so I wouldn't worry too much about getting the logs off.
