### ISSUE TITLE
Kodi Doesnt Display Subtitles

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-kodi#189]
Pinning this from the forums for @tazmanov 

https://forum.jellyfin.org/t/kodi-not-finding-embedded-subtitles/1345/3

Kodi is not detecting any embedded subrip (srt) subtitles.

**Comment by barolo** [comment]
I'm having similar issue [ since hevc/10bit->h264 accelerated transcode under amd/vaapi now actually works ]
Auto load [srt] doesn't seem to work.
Having subtitle selection before stream enabled, and picking it before, works but has tendency to desync.
Loading subs locally works best.

**Comment by leftl** [comment]
I've been chasing down a similar issue, but with embedded image subs that do not support external-streaming/subtitle-extraction. In my case it's an mkv with h264+PGSSub.
@barolo @Artiume do the the subs appear if you set the following setting ( Jellyfin settings -> Playback -> Enable audio/subtitle selection ) to Subtitles only, and select the appropriate subtitle subs on playback? This should work with or without transcode.

I noticed no **SubtitleStreamInex** is being passed to playlistutils in the **TranscodeURL**, even if subtitles do exist. If I add the value of **DefaultSubtitleStreamIndex** as the value for the parameter and append it to the **TranscodeURL** it works for this particular case. However, this may be incorrectly passing the **SubtitleStreamIndex** to other transcodes which I'm [still trying to debug](https://github.com/leftl/jellyfin-kodi/commit/e167bd5a7692f1fdcf4556084f2adb2619733f7b#diff-f9f2ca700fcc3f8919f4606f8fd6a541R258-R264). As far as I can tell, this issue is only effecting transcoded media with subtitle streams that do not support external streaming.

A couple questions this brings up: how reliable is the item ID **HasSubtitles** or is there a better way to check if subtitles are available from the item? Is the "smart" subtitle handling on the web client leveraging the server for the selection or is it all handled client side?

**Comment by barolo** [comment]
@leftl Situation changed since, with latest Jellyfin [ 10.5.3 ] subtitles [ srt ] get burned in [ I'm using HWA ] they work properly now and yes I have selection turned on.  
I'd prefer unburned since I could control positioning but I'll take what I can

**Comment by mobamoba** [comment]
Subtitles still don't work on external subs even with audio/subs enabled in Kodi/Jellyfin settings or subtitle only enabled in that same setting. I always have to go into browse and manually select the subtitle. When I playback the same video bypassing Jellyfin and just using SMB, the subtitle plays fine without any additional work on my part so it's something with this addon.

**Comment by mcarlton00** [comment]
I suspect there's multiple issues in play here:

* srt subs _should_ be working fine and I know I've seen them working on several of my installs, but I haven't used it too much lately
* While Kodi supports nearly any sub format, at last check the server was forcibly converting other formats to srt (https://github.com/jellyfin/jellyfin/issues/2239).  This then fails for anything that has images embedded in it since srt is text only

**Comment by mobamoba** [comment]
Mine are all SRTs and they work fine sometimes but not others. The one that prompted me to post here was a German show with English srts. When I started playing, there was no indication of any subtitles at all. I know it's different with different skins, but my skin show a little flag for both the audio language and the subtitle language. Until I manually loaded the subtitle, it was as if no subtitle was detected at all (and, yes, they were properly named and in the proper folder). With English audio and English subs, I don't have this problem, so could the language mismatch be part of the issue? No clue but just trying to help debug.

**Comment by iwatch-x** [comment]
@mcarlton00  Did you found anything new? cause i still have the problem the subs won't load ... also local as outside the network in kodi

**Comment by mcarlton00** [comment]
No.  I've been through over 50 of my movies with multiple external sub files and haven't found one fail yet.  Multiple languages, multiple naming standards.  srt subs are fine as far as I can tell.

* Movie.srt
* Movie.eng.srt
* Movie.en.forced.srt

**Comment by leftl** [comment]
Bit of a shot in the dark, but could it be a text encoding issue? I don't have any media with srt subs with the `Title` field containing special characters like ñ or ß.  Otherwise, srt subs are also working fine here (for the examples I have). 
@iwatch-x if you enable subtitle selection in the settings for the jellyfin add-on, are the subtitles listed? Do they appear in the media if selected?

**Comment by iwatch-x** [comment]
> 
> 
> Bit of a shot in the dark, but could it be a text encoding issue? I don't have any media with srt subs with the `Title` field containing special characters like ñ or ß. Otherwise, srt subs are also working fine here (for the examples I have).
> @iwatch-x if you enable subtitle selection in the settings for the jellyfin add-on, are the subtitles listed? Do they appear in the media if selected?

yes they appear i can select them first when the movie plays but then they become grey and cant select them again :/ only burnin  subs works :/

**Comment by iwatch-x** [comment]
> 
> 
> No. I've been through over 50 of my movies with multiple external sub files and haven't found one fail yet. Multiple languages, multiple naming standards. srt subs are fine as far as I can tell.
> 
>     * Movie.srt
> 
>     * Movie.eng.srt
> 
>     * Movie.en.forced.srt

all my movies are movie.nl.srt maybe try that?

**Comment by oddstr13** [comment]
@iwatch-x okay, so this is the information I'll need from you in order to start tracing down this problem:

1. Jellyfin server installation method: (Ubuntu repo / Docker / etc)
1. Full Jellyfin server version: (`10.2.4-1` / `jellyfin/jellyfin:10.2.4-amd64`)
  (For Debian/Ubuntu; `apt show jellyfin-server 2>/dev/null | grep -i version`)
1. Kodi version: (`16.6`)
1. Platform running Kodi: (`Raspberry Pi with LibreElec v3.4.2`)
1. Jellyfin for Kodi addon version: (`0.3.4`)

1. Full file names of the affected movie and subtitle file.
1. The `Media Info` section of the movie from Jellyfin

1. Full log file from Kodi;
    1. Enable debug loging in Jellyfin for Kodi settings 
    ![image](https://user-images.githubusercontent.com/638706/91743746-971d2180-ebb8-11ea-86eb-858faadab864.png)
    2. Restart Kodi. (Restart whole device if need be)
    3. Reproduce the issue
    4. Attach the full [Kodi log file](https://kodi.wiki/view/Log_file) to this issue

1. Relevant section of log from the Jellyfin server:
    1. Copy the section of the server log file from just before you restarted Kodi to after the issue has been reproduced.
    2. Attach the log snippet to this issue.

I may additionally need a copy of a failing subtitle file, but we'll take that later if it's required.

**Comment by iwatch-x** [comment]
@oddstr13 okay here we go 

1: Ubuntu 18.04.4 LTS docker
2:  linuxserver/jellyfin:10.6.4-1-ls71
3: Kodi v18.8 Leia
4: Nvidia Shield Pro (2019)
5: Version 0.5.8
6: The Outpost (2020) Bluray-1080p x265 AAC 5.1 Tigole & The Outpost (2020) Bluray-1080p x265 AAC 5.1 Tigole.nl.srt
7: [img]https://i.imgur.com/ZvA3w2j.jpg[/img]
8: Full Log https://paste.kodi.tv/atepicowor

**Comment by oddstr13** [comment]
Server log missing.
I'll have a look at it when I'm back at a computer.

On August 31, 2020 5:20:45 PM UTC, iwatch-x <notifications@github.com> wrote:
>@oddstr13 okay here we go 
>
>1: Ubuntu 18.04.4 LTS docker
>2:  linuxserver/jellyfin:10.6.4-1-ls71
>3: Kodi v18.8 Leia
>4: Nvidia Shield Pro (2019)
>5: Version 0.5.8
>6: The Outpost (2020) Bluray-1080p x265 AAC 5.1 Tigole & The Outpost
>(2020) Bluray-1080p x265 AAC 5.1 Tigole.nl.srt
>7: [img]https://i.imgur.com/ZvA3w2j.jpg[/img]
>8: Full Log https://paste.kodi.tv/atepicowor
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jellyfin/jellyfin-kodi/issues/189#issuecomment-683915630

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by oddstr13** [comment]
@iwatch-x Try disabling cinema mode in the addon settings, and restart Kodi
![image](https://user-images.githubusercontent.com/638706/91787242-b001f300-ec09-11ea-97b8-f1016cbe003e.png)

Steps to reproduce:
 1. Enable the Intros plugin (https://jellyfin.org/docs/general/server/plugins/index.html#dkanadas-repo)
 2. Pick an intro
 3. Make sure cinema mode is enabled in the addon
 4. Play a video with external subtitles

@mcarlton00 are you able to confirm that these steps does indeed cause no external subs?

**Comment by iwatch-x** [comment]
cinemamodus did it :O then the subs came back thnx but did you know whats the bug niw
