### ISSUE TITLE
Configure from config files, no cleartext password

### ISSUE THREAD

**Issue by Extarys** [jellyfin/jellyfin-kodi#353]
**Describe the issue**
I have multiple kodi/libreelec boxes at home and multiple users. All users have 50+ characters in their passwords. Configuring the plugin for each user on each boxes takes a lot of time as I have to type the password multiple times until it's "error-free".

I ssh into my testing box today to understand how I could configure everything from the console, but I think the jellyfin addon requests a token from the server instead of storing the password in clear text, which is awesome, but is it possible to get a token manually while I'm at my computer?

It would help if Kodi would allow seeing the characters in a password box.

**Suggestion**
- Add the ability to do this (if it's not already the case)
- Add documentation on how configure the addon from the shell

**System:**
 - OS: LibreElec
 - Jellyfin Version: 10.6.2
 - Kodi Version: 18.6
 - Addon Version: 0.5.8
 - Playback Mode: Native

**Additional context**
Passwords are long because I'm paranoid and also because the main server is exposed to the outside and even with fail2ban and other security measure, I don't want to risk it, so there is a strong password policy in place :smiley:

**Comment by mcarlton00** [comment]
Correct, we don't store the password at all, we rely on the authentication token that we get from the server.  There's no plans to change this from a security standpoint because we don't need to know users' passwords.  It might be possible to generate the authentication token from an external script, but it would likely also need to generate the device ID and name so it doesn't get conflicts in the server.  This isn't something we've looked into, and I can't say that I particularly like advertising that method as being available.  Seems very easy for users to wind up storing their passwords in plain text on the filesystem, which kinda defeats the purpose of strong passwords.

I see 2 easy alternatives that already exist:
* Use something like Kore so you can copy/paste passwords from your mobile device to your Kodi box.
* Utilize the "Easy Pin Code" login method on your users.  This is designed to only work on your LAN, so you'll have to make sure Jellyfin knows what your lan network is.  I'm also not entirely sure if it works in Kodi, but I believe it does.  I've never personally tested it

**Comment by Extarys** [comment]
@mcarlton00 Thanks for your reply. Of course I want to avoid storing password in plaintext and I'm glad it's not easily available for the average user to do so.

I used Kore to paste the passwords on one Kodi box. It works!
Although I had issues with kodi restarting when trying to connect a second user to a second profile.

Thanks for this suggestion! I'll do the other kodi boxes later - I'm watching TV now that it's working :laughing:
