### ISSUE TITLE
Version 0.5.9 is not in the kodi Repository

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [jellyfin/jellyfin-kodi#378]
Looks like the last version is not in the repository yet, there is only the 0.5.8. Could you add it please ? Thanks !!!
(I am talking about this repository https://kodi.jellyfin.org/repository.jellyfin.kodi.zip , that allows auto updates in Kodi)

**Comment by mcarlton00** [comment]
Yeah, unfortunately the new release pipeline we've started using didn't behave as expected.  Got a case of first time nerves I guess.  So it never got added to the repo.  The intention was to make another fairly quick release afterwards that fixed a few small issues so it wouldn't be a big deal, but obviously that hasn't happened yet because of irl things.  I need to reach out to the server admin and try to get them to run the commands manually.

**Comment by LeVraiRoiDHyrule** [comment]
> 
> 
> Yeah, unfortunately the new release pipeline we've started using didn't behave as expected. Got a case of first time nerves I guess. So it never got added to the repo. The intention was to make another fairly quick release afterwards that fixed a few small issues so it wouldn't be a big deal, but obviously that hasn't happened yet because of irl things. I need to reach out to the server admin and try to get them to run the commands manually.

Ok no problem. Thanks a lot for your detailed answer. Take all the time you need, you are doing a fantastic job !

**Comment by mcarlton00** [comment]
It's been added to the repos now.  All hail @joshuaboniface
