### ISSUE TITLE
Unable to sync music library

### ISSUE THREAD

**Issue by nellistc** [jellyfin/jellyfin-kodi#380]
**Describe the bug**
Attempt to sync music library fails. Video libraries sync successfully. Music library is able to be browsed as a dynamic library through the addon.

**To Reproduce**
1. Install latest jellyfin addon
2. Connect to jellyfin server
3. Attempt to sync music library
4. Sync fails with 'something went wrong' error. Kodi displays **Gathering: Music** status message and progress stays at 0%.

**Expected behavior**
Music library to be synced

**System (please complete the following information):**
 - OS: Linux
 - Jellyfin Version: 10.6.4
 - Kodi Version: 18.8 (libreelec 9.2.4)
 - Addon Version: 0.5.9-py2
 - Playback Mode: Add-on

**Additional information**

Initially, the request times out. If the DEFAULT_HTTP_TIMEOUT value is changed to a very long time (eg, 3000 seconds), the last line shown in the debug log is

2020-09-02 22:22:28.017 T:139790238344960  NOTICE: JELLYFIN.jellyfin.http -> DEBUG::jellyfin_kodi/jellyfin/http.py:162 ---<[ http ][77127 ms]

**Comment by mcarlton00** [comment]
77 seconds is a _long_ time for that api call.  Mine was only taking roughly 12 seconds to gather everything.  How large is your music library?

**Comment by nellistc** [comment]
It’s approximately 900 albums containing 12,700 songs.

The server is not fast, so this may be a contributing factor. However, it has been synced previously with an older version of kodi and the add on. (I cant be sure which versions.)

**Comment by nellistc** [comment]
The process (at least according to the logs) woke up about 11 hours after that last debug message and now I have the library in sync. Very strange.

**Comment by mcarlton00** [comment]
that's very odd.  My library is roughly 9000 songs and it was fine.  Being libreelec, I'm assuming this is a Pi or similar SBC?  Also was debug logging on when you were doing the sync initially, or did you turn it on after the fact and try again?

0.5.9 saw a pretty massive rework to the music syncing process, which if you've synced on previous versions then you probably understand why it was needed.  Basically, instead of making an api call for every single artist and album like in previous versions, now we just query the server for all artists, albums, and tracks in 3 calls and process them locally.  This causes the longer "gathering" delay waiting for the api to respond with all of those objects, but that time is more than made up in not having to make repeated calls to the api (Saves 15 minutes on my music sync).  #349 had the brunt of that work.

**Comment by nellistc** [comment]
JF is running on an ion desktop. Kodi client is running on a separate machine, same spec. Both connected via ethernet. 

I tried multiple times without debug logging, but it timed out each time. The last time (now with debug logging) was when I changed the default http timeout in the add on. 

The logs showed the requests for the content and the results were in the log before the 77 second message. Didn’t make sense that the front end showed 0% after it had retrieved a decent amount of content from the server.

Happy to zap it, test again and provide a log if you like.

**Comment by mcarlton00** [comment]
When you say it worked on a previous version, was this an upgrade or was it a fresh install?  I'm doing some testing on a raspberry pi to try to replicate this, but haven't had any luck yet.  The initial gathering data calls are slow, but it's working without errors.  Between hitting "ok" on the sync page and music starting to actually process, it's roughly 3 and a half minutes on a Pi 3 for my full library. But no timeout errors, so that's very odd.

The percentage is how much has been synced locally, not how much it's retrieved from the server.  So in that regard it's a bit deceptive.  This is the code that handles the music sync:
https://github.com/jellyfin/jellyfin-kodi/blob/c6de19cbf56b8e64017187d4abded81615bb7f27/jellyfin_kodi/full_sync.py#L420-L449

So it pulls all artists in one call, all albums in one call, and then all songs (this is the one that seemingly takes forever).  Since all this data is coming back in huge batches, we can't calculate a percentage complete there.  I do have an idea about how to change it up so the initial delay isn't as great, but it adds a bit of extra threading and code complexity.

**Comment by nellistc** [comment]
The client is a fresh install. Server was initially installed as 10.6 and has been upgraded to 10.6.4.

I've tried this from kodi on the server machine and it also failed -- I'll do some more testing and let you know the results.

**Comment by nellistc** [comment]
Ok, added some extra logging in so I could see where it stopped working, and .. it is now syncing as expected.

Grabbing the artists takes ~6s, the albums takes ~20s and then the songs takes around 5 and a half minutes. Adding the objects to the kodi instance is taking a while (5 minutes in and it's doing the Cs), but it's progressing and displaying the updates on the screen.

Might be time to close this one - it could well have been something in my local environment.

**Comment by mcarlton00** [comment]
Sounds like it could have been a blip of some kind.  Server hiccup, network blip, malformed packet, solar flare.  If it's working properly now, who knows.

It should _hopefully_ be significantly faster than syncing in previous versions just from the reduced number of api calls.  Though I've been thinking on this a lot today and the music sync does need to be reworked again.  Libraries like ours seem large, but I've been thinking of users who have 10s of thousands of songs (saw somebody on reddit mention 75k songs earlier).  The current process I've implemented is likely to crash and burn for those, so something needs to be changed still.  But that's an adventure for another issue.  If you're able to have sync working properly we're probably good to close this one out.  We'll see if your scan finishes successfully.

**Comment by nellistc** [comment]
It all finished, took about half an hour. I noticed the progress messages don’t necessarily have the artist displayed correctly beyond the first track on an album, so I might have a poke at that. Gives me an excuse to learn python 👍🏻

Thanks for taking a look at this.

**Comment by n-buck** [comment]
Hi, I'm experiencing a similar issue:
I tried to sync the music-library and after 12:20 min. I received an error-message (Something went wrong).
In this library are about 45'000 songs.
If any log-files would help you for this topic, I would be glad to share them.

**Comment by mcarlton00** [comment]
@nellistc  if you want a hint, the line you're looking to change for the artist display is in the code block I sent earlier.  The program flow around here is a bit challenging to follow at times, so feel free to ask if you have any questions.

@n-buck The Kodi logs would probably be helpful.  If it had an error it should be spit out there.  If you're on a device where they're not easy to get to, you can use the [log uploader addon](https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader).  The biggest question is whether it failed while gathering information, or while writing it to the database?

**Comment by n-buck** [comment]
Ah, the logfile uploader is neat, thanks for the hint.
[Here is the logfile](https://paste.kodi.tv/ewodijidiv).
It also times out during the api-call.
