### ISSUE TITLE
Cannot install addon version 0.5.9 or higher in Kodi 17

### ISSUE THREAD

**Issue by Panja0** [jellyfin/jellyfin-kodi#414]
**Describe the bug**
Cannot install the Jellyfin-kodi addon versions higher than 0.5.8
v0.5.8 is the latest version without the addition +py2 and can be installed.

**To Reproduce**

Install v0.5.9 or higher, either via the repo or manually

**Expected behavior**
Should just install updates higher than 0.5.8

**System (please complete the following information):**
 - OS: LibreElec
 - Jellyfin Version: 10.6.4
 - Kodi Version: 17.6
 - Addon Version: 0.5.8 is working, 0.5.9 or higher is not working
 - Playback Mode: does not apply

**Additional context**
Checked which version of Python is installed:
Python 2.7.13 (default, Jan 18 2018, 22:46:27) 
[GCC 6.2.0] on linux2

**Comment by oddstr13** [comment]
Could you please provide the [Kodi logs](https://kodi.wiki/view/Log_file)?

[LibreElec](https://libreelec.tv/) is available with Kodi 18.8, is there any particular reason for why you haven't updated yet?

Please do note that we are no longer testing Kodi 17, and as such it is per definition “unsupported”.

**Comment by Panja0** [comment]
Yes, specific reason is because I’m using a media player based on S905 chip. Kodi 17.6 is the latest available as far as I know. Correct me if I’m wrong! 😃

I’ll provide logs ASAP. Heading home in a few.

**Comment by Panja0** [comment]
@oddstr13 

I've enabled debug log and tried to install v0.6.2+py2 from the repo.
Here are the logs:
https://pastebin.com/AVkSQvei

**Comment by oddstr13** [comment]
The relevant section of the log seems to be:
```log
18:57:21.955 T:3789677472   DEBUG: CurlFile::Open(0xdd846d60) https://repo.jellyfin.org/releases/client/kodi/plugin.video.jellyfin/plugin.video.jellyfin-0.6.2+py2.zip
18:57:23.305 T:3789677472   DEBUG: CZipManager::GetZipList: failed to stat file zip://special%3a%2f%2fhome%2faddons%2fpackages%2fplugin.video.jellyfin-0.6.2%2bpy2.zip/
18:57:23.305 T:3789677472   ERROR: GetDirectory - Error getting zip://special%3a%2f%2fhome%2faddons%2fpackages%2fplugin.video.jellyfin-0.6.2%2bpy2.zip/
18:57:23.305 T:3789677472   ERROR: CAddonInstallJob[plugin.video.jellyfin]: invalid package special://home/addons/packages/plugin.video.jellyfin-0.6.2+py2.zip
```
With the error message being `invalid package`

**Comment by Panja0** [comment]
Ok, so why is it invalid?
I have tried to install it manually (download from github) and same problem. 

V0.5.8 works without problems...
It’s just not compatible anymore?

**Comment by oddstr13** [comment]
Okay, so after some testing I have some good, bad, and not so great news.

Good news is that downloading the zip and installing it manually works.

The bad news is that when Kodi 17.6 (at least on windows) downloads the file, it does a url-decode on the file name (including the silly `+` -> ` ` part), resulting in the downloaded file being saved as `plugin.video.jellyfin-0.6.2 py2.zip`, but Kodi is still trying to load a file named `plugin.video.jellyfin-0.6.2+py2.zip`.
I am not sure of how we could best handle this. The current versioning scheme was picked because it allows proper auto-updates when switching from Kodi 18 -> 19 (`x.y.z+py3` is a higher version number than `x.y.z+py2`, so Kodi will update this for you).
It may be sufficient to change how files are named on the server to something not including `+`, like replacing `+` with `_` in the code that adds the file to the repo.

The not so great news is that v0.6.2 seem to have multiple breaking bugs, resulting in difficulty setting up, syncing and playing content. I got it syncing my movie library after fiddling a little, but playback isn't working. I haven't looked into the details here yet.

---

Full [non-debug log](https://github.com/jellyfin/jellyfin-kodi/files/5411001/kodi17.log) of my testing session.

**Comment by Panja0** [comment]
Thanks for testing! 👍🏻
So would it be better (for now) to install v0.6.1? And do I need to rename the zip?
Because I tried installing v0.6.2 from github, downloaded on my Windows machine. Copy to usb and than install from usb within Kodi. 
That didn’t work for me.

**Comment by oddstr13** [comment]
This is where you'd want to download the releases from now: https://repo.jellyfin.org/releases/client/kodi/py2/plugin.video.jellyfin/

With the py2/py3 split, the repo no longer contains addon.xml, only the template and variables to generate it, and as such, just downloading the zip file generated by GitHub is no longer sufficient.

It looks like video playback broke for Kodi 17 with v0.5.9 due to #346, so there is no point in updating for you now, at least as long as v0.5.8 still works for you.

**Comment by Panja0** [comment]
So I can add this repo to Kodi right?
If so I will try the latest (0.6.2) with native mode and report back.

**Comment by oddstr13** [comment]
That is the repo added by the repo addon, for Kodi 17 you'll have to manually download and install the zip unfortunately, due to the url-unescape bug in Kodi 17.
https://repo.jellyfin.org/releases/client/kodi/py2/plugin.video.jellyfin/plugin.video.jellyfin-0.6.2%2Bpy2.zip

**Comment by Panja0** [comment]
Ok, understood!
I’ll give it a go and report back. 
Thanks for all the help.

**Comment by Panja0** [comment]
@oddstr13 
I have some good news.... 
And some good news and some more good news.
And a little bad news...

I managed to install the addon (v0.6.2+py2) manually, as suggested. I did a wget https://etcetcetc through SSH and installed the zip. Set it up with native mode and playback seems to be working fine! Resuming movies or play from beginning is working as well. Last good news is that my device (Mecool M8S Pro+) seems to be still supported on CoreELEC. So if I switch from LibreELEC to CoreELEC I can have Kodi 18.8!

Bad news... I have to get a new SD card to test CoreELEC out! :-P

**Comment by mcarlton00** [comment]
Now that Kodi 19 is out and stable, and given that Kodi 17 is so old and hasn't received any updates since 2017, we've made the decision to stop supporting it.  If the code itself keeps working, great.  We're not going to purposefully break compatibility.  But with our limited dev team and limited amount of time, it's just not feasible to continue to support Kodi 17 at this point.  Apologies to whoever is stuck on old versions.
