### ISSUE TITLE
Unable to 'Manually add server' when a server has been auto detected

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellyfin-kodi#440]
**Describe the bug**

On the server setup menu, it's impossible to arrow down to the 'Manually add server' button when there's been an server that has been auto detected.

**To Reproduce**

1. Have server A set up for auto detect
2. Fresh install addon, go through server setup
3. Can't arrow down paste autodetected server

**Expected behavior**

duh

**System (please complete the following information):**
 - OS: Big issue on anything without a mouse
 - Kodi Version: 18.9
 - Addon Version: 0.6.5

Original reported: https://www.reddit.com/r/jellyfin/comments/k5w7p4/cant_connect_to_jellyfin_server_via_kodi/

**Comment by nearcatch** [comment]
I'm having the exact same issue as that redditor. Trying to connect Kodi on my Nvidia Shield to Jellyfin and it won't work. Can't arrow down, had to connect a mouse. Jellyfin server is auto-detected but can't be connected to, and then putting in the server and port manually closes the window with no further messages. After a few seconds the window pops back up asking me to choose a server again.

The interesting thing is this exact same server name and port works fine to connect the iPhone app to Jellyfin. And for giggles I loaded Kodi onto my iPhone and tried connecting there, and it wouldn't work. So the iOS Jellyfin app can connect via jellyfin.lan:8096, but iOS Kodi app fails silently with the same server.

So that reddit post has two issues:
1. can't arrow down (relatively minor)
2. kodi jellyfin addon is not accepting manually typed server that is valid (completely breaking)

**Comment by mcarlton00** [comment]
My guess here is that when a server has been autodetected, the addon sees no reason why it should ever _not_ use the auto detected URL and refuses to use a different one for that particular server.  Which is a fair assumption in a lot of cases, but docker containers that haven't been configured for that are going to lead to issues

**Comment by nearcatch** [comment]
I don't know that it's a fair assumption when the addon is ignoring manual user input. If a user explicitly chooses the gui to *not* use the autodetected url, the addon should respect that and use whatever IP or port is specified.

It would also solve almost all docker container problems if you could just forward 8096 or 8920 to the docker host and then manually specify the IP yourself.

**Comment by mcarlton00** [comment]
It's a fair assumption in the sense that when somebody has specifically enabled autodiscovery on their server, you expect that to be used.  Obviously it's wrong in certain cases when the container hasn't been fully configured (like telling it to use a different address with an environment variable), but in the large majority of cases yes, it should be a fair assumption.  However, it still shouldn't be overriding the manual entry, which is why I've said it still needs to be looked into in the other places this was discussed.

Also, only port 7359 is used for autodiscovery.  I'm not sure what 1900 is for.  
https://github.com/jellyfin/jellyfin-kodi/blob/f943316d2525469b066d1478796c120c155c813a/jellyfin_kodi/jellyfin/connection_manager.py#L213-L215

**Comment by nearcatch** [comment]
> Also, only port 7359 is used for autodiscovery. I'm not sure what 1900 is for.
Those ports are copy/pasted from lsio's jellyfin page. They reference the [official jellyfin networking page](https://jellyfin.org/docs/general/networking/index.html#port-bindings) which does mention 1900.

**Comment by oddstr13** [comment]
`1900` is for UPnP / SSDP, and is not used by this addon for discovery.
That is what you would use to play via UPnP without using this addon.
