### ISSUE TITLE
Installing Master

### ISSUE THREAD

**Issue by TheNamelessWonderer** [jellyfin/jellyfin-kodi#457]
Hello, I would like install master as it has some fixes for 10.7. However, there doesn't seem to be any instructions to do so. Would it be possible to quickly explain how? Seeing as it is python I assume nothing needs to be compiled.
Thank you

**Comment by mcarlton00** [comment]
Related to #405 that we still haven't agreed on because we're all petty and disagreeable.

The short version is that you need to make the `addon.xml` file and include it in the root of the repo, and then zip that up to install into Kodi.  An easier solution is probably to check the azure pipelines and install the latest run for a merged PR.  Here are the current latest built addons from a PR: https://dev.azure.com/jellyfin-project/jellyfin/_build/results?buildId=21904&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by TheGreatestJannet** [comment]
Thank you very much! I’ll try the latest run. Just to confirm but the plugin doesn’t work with 10.7 currently right or is it just minor issue that don’t fully prevent the plugin from functioning?

**Comment by TheNamelessWonderer** [comment]
Thank you very much! I’ll try the latest run. Just to confirm but the plugin doesn’t work with 10.7 currently right or is it just minor issue that don’t fully prevent the plugin from functioning?

**Comment by mcarlton00** [comment]
The current release (0.6.5) doesn't fully work with 10.7, no.  Master does, but with the caveat that the server has some bugs that makes upgrading from 10.6.4 to 10.7-rc1 force a library resync in Kodi.  Those were fixed in the server, but has the side effect of upgrading from 10.7-rc1 to 10.7-rc2 (when it comes out) will also force a library resync in Kodi as it goes back to the previous behavior.

**Comment by TheNamelessWonderer** [comment]
Thank you very much for your help. I’m still on 10.6.4 but looking to upgrade soon.
