### ISSUE TITLE
fails on kodi 19 with python 3

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin-kodi#477]
Trying to install the plugin on Kodi 19 fails pretty terribly.  Working around https://repo.jellyfin.org/releases/client/kodi/ layout and repository.jellyfin.kodi/addon.xml mismatching, I finally get:

```
2021-02-28 15:24:03.840 T:1662    ERROR <general>: CAddonInstallJob[plugin.video.jellyfin]: The dependency on script.module.requests version 2.22.0+matrix.1 could not be satisfied.
2021-02-28 15:24:03.926 T:1664    ERROR <general>: CCurlFile::Stat - Failed: Couldn't connect to server(7) for https://repo.jellyfin.org/releases/client/kodi/plugin.video.jellyfin/resources/icon.png
```

**Comment by mcarlton00** [comment]
I'm not sure what you mean by the `addon.xml` not matching, but the requests issue is from upstream.  It means that whatever upstream Kodi addon mirror your system is using is out of whack and doesn't have the proper versions available.  Nothing we can do about it.  Typically you need to just wait it out until it gets fixed or your system uses a different one, or manually install that dependency.  I've heard talk that if you refresh the repo metadata (Addons -> Install from repo -> highlight repo -> Right click/c/long click to get the context menu and select "Check for updates") will sometimes fix it.

**Comment by brianjmurrell** [comment]
2021-02-28 15:24:03.926 T:1664    ERROR <general>: CCurlFile::Stat - Failed: Couldn't connect to server(7) for https://repo.jellyfin.org/releases/client/kodi/plugin.video.jellyfin/resources/icon.png

is because that URL doesn't actually exist.  That's on **your** server, not some "upstream" server anywhere else that you do not have control over.

That resource actually doesn't even exist in https://repo.jellyfin.org/releases/client/kodi/py3/plugin.video.jellyfin/ like it does in https://repo.jellyfin.org/releases/client/kodi/py2/plugin.video.jellyfin/.

**Comment by mcarlton00** [comment]
It's also a harmless error that means nothing.  It just means that you won't have the icon while browsing the repo, it doesn't prevent anything from working properly.

> CAddonInstallJob[plugin.video.jellyfin]: The dependency on script.module.requests version 2.22.0+matrix.1 could not be satisfied.

This is where your issue lies.  requests is not in our repo, it's in Kodi's repos, and apparently when you tried to install you connected to a mirror that didn't have the proper data.

**Comment by OdinGitDat** [comment]
I have the same problem, do you suggest to open another issue in another repo?

**Comment by mcarlton00** [comment]
As far as I know, when the upstream mirrors are misbehaving then the only solution is to just wait it out.  I've found it usually fixes itself within a day.  Sometimes if you delete the kodi config directory and start totally fresh it will go through, but that seems to be pretty hit or miss in my experience.

**Comment by brianjmurrell** [comment]
> delete the kodi config directory

Which directory do you mean by that?  Does that result in resetting **all** of Kodi's preferences back to default and one then has to go through and re-make all of the changes they have made to Kodi's config over time?  If so, that is waaaaaaaay too big of a hammer.

**Comment by oddstr13** [comment]
> Which directory do you mean by that?

`~/.kodi/`
`%APPDATA%\Kodi` I think?

> Does that result in resetting all of Kodi's preferences back to default

Yes.

**Comment by mcarlton00** [comment]
The other option is to manually download whatever dependency has failed and install it via a zip file.  This isn't recommended because then it likely won't be automatically updated in the future when updates are released to the repo, but it works in the interim.

https://mirrors.kodi.tv/addons/matrix/script.module.requests/script.module.requests-2.22.0+matrix.1.zip?mirrorlist

**Comment by oddstr13** [comment]
> Working around https://repo.jellyfin.org/releases/client/kodi/ layout and repository.jellyfin.kodi/addon.xml mismatching

Could you please be a bit more specific about what exactly you are trying to say here?

Following the steps to install via the addon repo here *should* just work. https://jellyfin.org/docs/general/clients/kodi.html#install-add-on-repository
If it doesn't, we'll need more information about your setup in order to figure out why it isn't working.
