### ISSUE TITLE
Sync never completes because the API fails on certain items

### ISSUE THREAD

**Issue by richardbrodie** [jellyfin/jellyfin-kodi#491]
**Describe the bug**
Sync hangs partway through when API thows an exception on an item with malformed metadata. Related to https://github.com/jellyfin/jellyfin/issues/5486

**To Reproduce**
1. Have an item with bad metadata somehow
2. Start library sync
3. Server fails to serialise one episode and throws an exception
4. Sync hangs instead of skipping item

**Expected behavior**
Sync should skip item and continue

**System (please complete the following information):**
 - OS: [e.g. Android, Debian, Windows]
 - Jellyfin Version: [e.g. 10.0.1]
 - Kodi Version: [e.g. 18.3]
 - Addon Version: [e.g. 0.2.1]
 - Playback Mode: [e.g. Add-On or Native]

**Comment by mcarlton00** [comment]
I don't think we should address this client side.  If we skip bad items, it effectively means those items are never going to be synced unless the user does manual intervention down the road.  That's not a particularly good solution, imo.  Especially because of the way our API calls are batched, skipping a single bad episode effectively means that you might actually skip an entire season or show instead.  There's no way to filter further than that and maintain any semblance of performance during the sync.  I can understand the frustration if you're unable to use a client due to a server bug, but I feel like that should be addressed in the server instead of us implementing workarounds for issues that shouldn't ever occur during normal usage.

**Comment by richardbrodie** [comment]
I understand what you're saying, and I agree this is definitely a server side bug. But failing catastrophically because of an upstream bug seems like a less than ideal way to handle it. I would say this failure mode is a seperate issue that should still be addressed.
