### ISSUE TITLE
Watched status not being synced

### ISSUE THREAD

**Issue by johnvick** [jellyfin/jellyfin-kodi#50]
I am using Kodi 18.3, Jellyfin server 10.3.7, Kodi sync queue 2.0.0.0 and the jellyfin-kodi plugin 0.2.1. Jellyfin is on ubuntu server 18.04, Kodi on Windows 10 and Android TV (same behaviour on both).

New episodes are added to Kodi fine but watched status is not - for example, I watch an episode using the Jellyfin web interface and it is ticked off as watched. I start Kodi and the episode I just watched on Jellyfin web interface is not marked as watched. If I go to the plugin and manually update the libraries it syncs the watched status. Synching works the other way Kodi -> Jellyfin without manual intervention.

Any suggestions how to get the two way watched status syncing? Would posting logs help and if so which ones?

**Comment by johnvick** [comment]
Pleased to report I have solved this. In the Jellyfin-Kodi plugin I had Kodi companion enabled but disabling and then reenabling it solved the problem.

**Comment by oddstr13** [comment]
I've seen this happen once, where the playback was in Kodi.
It synced back to Jellyfin just fine, but never synced back to Kodi.
(From my experience, when it syncs watched state after playback, it's a 2-way sync - watched state swaps. Then a little after the watched state gets corrected in Kodi again).

I forgot to save logs, but I'll try to remember if I ever see the issue again.

It is good that you found an easy workaround, but considering there hasn't been any changes in either kodi-sync-queue or jellyfin-kodi, and the fact that it has happened on at least two different systems, I think this is still an issue.

**Comment by johnvick** [comment]
I've checked this out a bit more and the fix I found above is a temporary one and has to be reapplied when Kodi is restarted.

**Comment by johnvick** [comment]
More research on this has led me to the conclusion that if Jellyfin and Kodi (or Kodis) are all running then two way sync of watched status happens near instantly. If a Kodi is off, and an episode is watched on another device, the watched status is not synced when the Kodi is powered up - unless you do a manual library sync or disable/reenable Kodi companion plugin. Tested with 2x Windows 10 and 1 x Android TV i.e. three Kodi instances and all behave same way.

**Comment by EvilAaron** [comment]
I am noticing this as the family here watches content on 3 different Kodi installs that are not always on. I am also using Trakt plugin on Jellyfin server so was not sure what the culprit was and found this searching.

Any way to automate Kodi to do a Jellyfin library sync or update on Kodi startup to pull any missing watched statuses from any use on other installs that occurred while shutdown?

**Comment by quixventure** [comment]
Also having the same issue. All of my always-on LibreElec clients are updating correctly, but a windows install that I Use occasionally is not syncing properly. 

It DOES show the Kodi sync stuff at start up (i.e. XX updates and XX% complete, and it will finish the update), but it seems to miss a lot of updates. Some updates process but others do not... It seems rather inconsistent right now but I have not done any formal testing.

**Comment by johnvick** [comment]
I have setup Jellyfin 10.4 with Kodi plugin 0.3.4 just to test this - but the problem persists - watched status is not sync'd on Kodi machine that are not on all the time.

**Comment by nummersyv** [comment]
Any updates on this issue? It's pretty much my only problem with using Jellyfin+Kodi at the moment.

**Comment by Ky-0** [comment]
Yep same issue here, any updates on the status of this - I am running the latest version of JF for Kodi (0.3.6)?

**Comment by mcarlton00** [comment]
I've confirmed this is still happening, mostly affecting systems that aren't on 24/7.  I've started looking into it, but haven't found anything conclusive yet.  It always syncs library updates, but doesn't always catch the watched status.

**Comment by Bryan792** [comment]
As a workaround, it would be cool if we could schedule regular full updates

**Comment by KaXaSA** [comment]
I have the same issue (I think), I also don't leave Jellyfin/Kodi running all day. I watch mostly on my TV, but every now and then I use my PC and every time I change from one to the other I have to open **addons > Jellyfin > manage libraries > update libraries** to force it to sync. -I don't know if there is an easier way to do this-

If I could force Kodi to automatically update the Jellyfin libraries when I open the program that would probably work. I tried to check an option in Kodi  'media settings > video library > update library on startup' but I assume it doesn't work on Jellyfin addon?

**Comment by mcarlton00** [comment]
Yeah, that sounds like the same issue.  At this point, I'm pretty sure the underlying cause is a bug in the Kodi sync queue plugin that gets installed into the server.  It's returning library content updates (items added/removed), but it isn't returning any user data (watched status).  Manually triggering a re-scan like @KaXaSA mentioned does seem to pick up new watched status.

The addon already does a sync on startup, but it's largely dependent on the server plugin to know what data needs to be synced.  I _should_ be able to trigger a full scan on startup instead of relying on what the server returns.  I've been hesitant to change this behavior since it has the potential to increase startup times with redundant scanning, but at this point it seems like it may be worthwhile to at least put a temporary override (maybe even a full fledged config option, but that's more time intensive to set up) to ignore what the server plugin says and try to fetch everything.

**Comment by caspervk** [comment]
Isn't it more viable to fix the issue on the server-side, ensuring that it returns user data?

**Comment by mcarlton00** [comment]
That's absolutely the desired fix, yes, which is why I opened that other issue. But that requires getting somebody who knows C# and is familiar with (or willing to learn) the server plugin API to work on it. I don't fit either of those, unfortunately. I have tried to look into it, but I wasn't able to get very far into debugging.

**Comment by dtorner** [comment]
I have compiled the latest plugin source and made some tests, now It's working as expected.

**Comment by johnvick** [comment]
Nice to know this has been fixed - how can it be installed or will it just come through automatically as an update?

**Comment by TrueTechy** [comment]
The fix is on the server side plugin. When a new version is release then the sever should pick that up and install it automatically

**Comment by dtorner** [comment]
Maybe this fix would be enough to tag a new version of the plugin to get an update. it's a small change, but makes a big difference...

**Comment by TrueTechy** [comment]
It has been, just waiting for final approval on it to be released https://github.com/jellyfin/jellyfin-plugin-kodisyncqueue/pull/18

**Comment by FallenLeave91** [comment]
> It has been, just waiting for final approval on it to be released [jellyfin/jellyfin-plugin-kodisyncqueue#18](https://github.com/jellyfin/jellyfin-plugin-kodisyncqueue/pull/18)

This fixed it for me :)
