### ISSUE TITLE
Kodi Categories missing for Movies and TV Shows

### ISSUE THREAD

**Issue by TheNamelessWonderer** [jellyfin/jellyfin-kodi#514]
**Describe the bug**
The Kodi categories is missing for TV Shows and Movies but is there for Music.

**To Reproduce**

1. Install Kodi
2. Install Jellyfin Plugin
3. Sync Libraries

**Expected behavior**
The Kodi categories bar should appear.

**Logs**

I have this error being constantly spammed but it seems irrelevant as this is my first sync.
```
2021-05-01 18:05:56.968 T:1555452800   DEBUG: CSettingsManager: requested setting (MinimumSetup) was not found.
2021-05-01 18:05:56.968 T:1555452800   DEBUG: CAddonSettings[plugin.video.jellyfin]: failed to find definition for setting MinimumSetup. Creating a setting on-the-fly...
2021-05-01 18:05:56.968 T:1555452800   DEBUG: CSettingsManager: requested setting (MusicRescan) was not found.
2021-05-01 18:05:56.968 T:1555452800   DEBUG: CAddonSettings[plugin.video.jellyfin]: failed to find definition for setting MusicRescan. Creating a setting on-the-fly...
2021-05-01 18:05:56.968 T:1555452800   DEBUG: CSettingsManager: requested setting (SyncInstallRunDone) was not found.
2021-05-01 18:05:56.968 T:1555452800   DEBUG: CAddonSettings[plugin.video.jellyfin]: failed to find definition for setting SyncInstallRunDone. Creating a setting on-the-fly...
2021-05-01 18:05:56.968 T:1555452800   DEBUG: CSettingsManager: requested setting (groupedSets) was not found.
2021-05-01 18:05:56.968 T:1555452800   DEBUG: CAddonSettings[plugin.video.jellyfin]: failed to find definition for setting groupedSets. Creating a setting on-the-fly...
2021-05-01 18:05:56.968 T:1555452800   DEBUG: CSettingsManager: requested setting (platformDetected) was not found.
2021-05-01 18:05:56.968 T:1555452800   DEBUG: CAddonSettings[plugin.video.jellyfin]: failed to find definition for setting platformDetected. Creating a setting on-the-fly...
2021-05-01 18:05:56.974 T:1555452800   DEBUG: CAddonSettings[plugin.video.jellyfin]: loading setting definitions
2021-05-01 18:05:56.974 T:1555452800   DEBUG: CAddonSettings[plugin.video.jellyfin]: trying to load setting definitions from old format...
2021-05-01 18:05:56.978 T:1555452800   DEBUG: CAddonSettings[plugin.video.jellyfin]: loading setting values
2021-05-01 18:05:56.979 T:1555452800   DEBUG: CSettingsManager: requested setting (LastIncrementalSync) was not found.
2021-05-01 18:05:56.979 T:1555452800   DEBUG: CAddonSettings[plugin.video.jellyfin]: failed to find definition for setting LastIncrementalSync. Creating a setting on-the-fly...
```
**Screenshots**
What I see:

![ima_1e25ee1](https://user-images.githubusercontent.com/56267607/116790635-3af30000-aaad-11eb-914c-ba76d35867fd.jpeg)
What I should see:
![whatIshouldhave](https://user-images.githubusercontent.com/56267607/116790641-4514fe80-aaad-11eb-8cce-1a49e7c3c17b.jpg)

**System (please complete the following information):**
 - OS: LibreElec 9.2
 - Jellyfin Version: 10.7.2
 - Kodi Version: 18.9
 - Addon Version: 0.7.2
 - Playback Mode: Add-on

**Additional context**

I may be wrong and this could be unrelated to the Jellyfin Kodi Plugin but I don't have any other plugin installed or get media in any other way.

My theory is that it is not grabbing something that is required for that for it to appear. This use to work fine and the bar would appear but since I did a fresh install today I can't get it to appear.

**Comment by TheNamelessWonderer** [comment]
Just tried with local files and the categories appear just fine. This means that it seems to be a bug with the plugin.

**Comment by TheNamelessWonderer** [comment]
I have tried 0.7.0, 0.7.1 and 0.7.2 and they all have the same issue.

**Comment by TheNamelessWonderer** [comment]
I have tried normal Kodi 19 on Ubuntu and I can confirm that the Issue is also present there as well.

**Comment by mcarlton00** [comment]
My guess it's it's a database flag that's not being populated.  Since it's not exactly documented nicely, it'll be a bit of trial and error to figure out why.  Iirc, then people/cast info also isn't working on shows.  I spent several hours trying to find that one a few months ago and never figured out where it was being called from.

**Comment by TheNamelessWonderer** [comment]
Ah I see. It use to work before. Definitely with 10.6 release so something must have changed either with 10.7 or one of the 0.7.* releases of the plugin.

**Comment by mcarlton00** [comment]
Alright, so definitely not a database flag.  This is where the custom xml nodes can come into play.  They can be made custom by using the [Library Node Editor](https://kodi.wiki/view/Add-on:Library_Node_Editor) addon and going to `Settings -> Interface -> Configure skin -> Main menu items` and Edit categories of whatever you'd like.  It looks like it's putting these into `$KODI_HOME/userdata/library/videos/{movies/tvshows}`, while the ones that we're generating in the addon are being populated in `$KODI_HOME/userdata/library/videos/jellyfin{movies/tvshows}{library_id}`.  It seems as though if there's anything in that 'videos' directory, it refuses to use Kodi's default values.  Which means that I guess #426 was a mistake and I'll need to find a way to add that back in.  But it was apparently breaking the addon on the new AppleTV, so that might take some effort to work around.

**Comment by TheNamelessWonderer** [comment]
Are these created once or at every sync? Let’s say I delete the files in there and perhaps make it read only the categories should come back right? The latter might be slightly challenging as LibreElec runs as root I believe.

**Comment by mcarlton00** [comment]
Ours files are generated every time Kodi starts.  I copied our files to `$KODI_HOME/userdata/library/videos/tvshows` and it did make the categories show up again, but they didn't work properly.  Every category would just redirect you to a stripped down addon menu.  So basically it seems like we need to copy the default values over, but find a way to do it that doesn't break AppleTV systems.  Or at the very least, not make that a blocking issue if it fails.

**Comment by TheGreatestJannet** [comment]
Do you mean MrMC or Kodi on a jailbroken AppleTV? Also wouldn't it be possible to detect that the user is using an AppleTV and disable this feature to prevent it from crashing.

**Comment by TheNamelessWonderer** [comment]
Do you mean MrMC or Kodi on a jailbroken AppleTV? Also wouldn't it be possible to detect that the user is using an AppleTV and disable this feature to prevent it from breaking on AppleTV systems but allow other users to still be able to use it.

**Comment by arcoast** [comment]
FWIW I've hit this issue too, I used this feature regularly to split between kids programmes and adult programmes, I've managed to kind of work around it by using the Amber skin and setting up some custom stuff, but it would be great if it could be fixed.

**Comment by mcarlton00** [comment]
Just want to chime in.  I haven't forgotten about this.  It's on my list to get to, but it might not be for a while.  I'm in the midst of a housing shuffle at the moment so my time for coding is limited.

@TheNamelessWonderer I'm not sure how Kodi was installed.  Kodi's documentation does appear to be using a jailbroken AppleTV [link](https://kodi.wiki/view/HOW-TO:Install_Kodi_on_Apple_TV_4_and_5_(HD_and_4K)).  MrMC is a totally different app and to my knowledge Kodi addons won't work on it, though I could be wrong there.

Ideally we'd be able to find where the files are _meant_ to be in an AppleTV and make it work properly there, but since I don't have any apple products that may be a challenge to debug here.  Worst case scenario I'll basically revert #226, but exclude it on AppleTV devices.

**Comment by jfranki** [comment]
Don't focus only on the AppleTV. I have this issue on an Intel NUC with Windows, and the categories widget is missing in both the UWP store Kodi and the win32 Kodi.
Other 2 clients (one Raspberry Pi 4 and one Intel NUC with Libreelec) DO NOT have this issue with the same Jellyfin server. The only difference is that the one device that is suffering this bug is that is on the same network as the server, maybe that could point you in the right direction (or not).

**Comment by TheNamelessWonderer** [comment]
Is it a fresh install on your LibreELEC devices? I have a Raspberry Pi 3B+ and have this issue with LibreELEC 9.2.7

**Comment by mcarlton00** [comment]
This is currently broken for you because the old approach was broken on AppleTV, and we didn't realize the categories were reliant on it (because I don't use them).  That's the basis for all of this.

See https://github.com/jellyfin/jellyfin-kodi/issues/422, but the TLDR is that the files we need don't exist where they're supposed to exist on AppleTV.  It was preventing the startup wizard from ever running and making the whole addon unusable.  So we removed that function and didn't see any adverse effects (because again, we don't use categories and didn't notice it).  The solution is to put that function back, but figure out a way to have it not prevent AppleTV devices from running.

**Comment by TheNamelessWonderer** [comment]
Isn’t this a bug with Kodi for AppleTV? If so has it been reported upstream so that it could be potentially resolved?

**Comment by mcarlton00** [comment]
Possibly, yes.  I can reach out to the Kodi folks and ask them.  At the time it didn't seem important, so we didn't spend much more time looking into it than necessary.

**Comment by neo-neo1** [comment]
Also experiencing this currently with the Jellyfin Kodi Addon

**Comment by jfranki** [comment]
> Don't focus only on the AppleTV. I have this issue on an Intel NUC with Windows, and the categories widget is missing in both the UWP store Kodi and the win32 Kodi.
> Other 2 clients (one Raspberry Pi 4 and one Intel NUC with Libreelec) DO NOT have this issue with the same Jellyfin server. The only difference is that the one device that is suffering this bug is on the same network as the server, maybe that could point you in the right direction (or not).

I don't know when, but the bug reproduced in my Libreelec (10.0.2) too... I'm afraid I can't figure out what triggered the widget's disappearance. To fix it I did what @jasondaigo posted and it seems that categories persist between reboots, so fingers closed.

- Jellyfin Server 10.7.6 (Docker with reverse proxy)
- Libreelec 10.0.2 (Kodi 19.4)
- jellyfin-kodi 0.7.7 (updated to 0.7.8-9 but issue persisted)
