### ISSUE TITLE
0.7.3 crashes Kodi

### ISSUE THREAD

**Issue by venomousZealot** [jellyfin/jellyfin-kodi#520]
The new release crashes Kodi when trying to play back anything or accessing some settings. Syncing seems to work.
0.7.2 works

There isn't anything in the logs as far as I can tell, but here it is anyway:
[kodi_crashlog-20210510_172111.log](https://github.com/jellyfin/jellyfin-kodi/files/6453179/kodi_crashlog-20210510_172111.log)

I managed to do a git bisect, since I didn't know what else to do and this is the result:
```
979c07723101eb1215bce6de2f199cb0cc33c54c is the first bad commit
commit 979c07723101eb1215bce6de2f199cb0cc33c54c
Author: Matt <mcarlton00@gmail.com>
Date:   Sat Jun 20 18:10:36 2020 -0400

    Move websocket to a dependency

 jellyfin_kodi/jellyfin/websocket.py | 940 ------------------------------------
 jellyfin_kodi/jellyfin/ws_client.py |   4 +-
 2 files changed, 2 insertions(+), 942 deletions(-)
 delete mode 100644 jellyfin_kodi/jellyfin/websocket.py
```

**Comment by mcarlton00** [comment]
I've narrowed it down to being an interaction between Kodi and numpy installed to the OS.  Which also explains why it's not happening on a minimal amount of devices.

On Windows, Kodi contains it's own embedded Python, so there's no environment bleed.  I believe the same is true on Android based devices as well.

On Linux, Kodi uses the system Python and can pick up system libraries.  This means that even though numpy isn't installed in Kodi (and isn't packaged for Kodi in anyway), if it's installed on the OS then it's possible for Kodi to import it.  If I have numpy installed, then Kodi will crash on playback.  If I remove it, then everything works as expected.  Since it boils down to numpy installed to the OS, this is also highly unlikely to impact systems like LibreElec or OSMC, and only hits people using Kodi on their workstations.  So this is either a bug in the upstream library, or maybe our `ws_client.py` needs to be tweaked some more to avoid whatever is happening. I hate this library.

**Comment by venomousZealot** [comment]
Can confirm this fixed it. Awesome!
