### ISSUE TITLE
Dependency not satisfied when installing on kodi 17.6

### ISSUE THREAD

**Issue by n00bhax** [jellyfin/jellyfin-kodi#540]
### **Describe the bug**
I'm trying to get jellyfin-kodi on my steam link (og hardware). 
It's running kodi 17.6 from https://github.com/garbear/kodi-steamlink
I followed this guide: https://jellyfin.org/docs/general/clients/kodi.html
Everything went fine until an error occured when clicking install:
**"The dependency on xbmc.python version 2.26.0 could not be satisfied"**

### **System (please complete the following information):**
 - Kodi Version: 17.6
 - Addon Version: 0.7.4

**Comment by mcarlton00** [comment]
2.26 is the python version used in Kodi 18.  We're defining version 2.25 for use in python 2 builds so that Kodi 17 _should_ still work.  There's every possibility that one of our other dependencies has dropped support for Kodi 17 and older, in which case it's largely out of our hands.  Unfortunately, Kodi 17 is also  absolutely ancient and none of us have dev machines old enough to still effectively work on it, so it really works largely by luck.  Kodi 19 is out and stable now, I highly recommend you upgrade instead of using a version that hasn't received an update since [2017](https://kodi.tv/article/kodi-v176-final-very-last/).
