### ISSUE TITLE
Browse in "Show information" context menu sends you to the main addon menu

### ISSUE THREAD

**Issue by krutburken** [jellyfin/jellyfin-kodi#548]
**Describe the bug**
Blatant copy paste from a reddit post: https://www.reddit.com/r/jellyfin/comments/oinv8k/kodi_browse_button_for_tv_shows_take_you_to_the/

**To Reproduce**
1. Set default action to show information
2. Click on a show in "In progress" for example
3. Click Browse at the bottom left
4. Get sent to the main addon menu

**Expected behavior**
You should be sent to the list of seasons for this show

**Screenshots**
> If you start from the Home Screen > TV Shows > In Progress and select one, you get [here](https://imgur.com/CkiXVmU)
The folder icon at the bottom left there is Browse, which I expect would send you to the list of seasons for this show, but instead you end up [here](https://imgur.com/TqyCGHg)

**System (please complete the following information):**
 - OS: Android tv
 - Jellyfin 10.7.6
 - Kodi 19.1
 - Addon 0.7.4

**Comment by mcarlton00** [comment]
Additional note: Step 1 can be skipped.  It happens when you open the context menu manually as well (right click/long click/c).

Issue is caused by Kodi sending the addon a signal that contains a URL, but no actual command.  We need to make another case to catch this in https://github.com/jellyfin/jellyfin-kodi/blob/master/jellyfin_kodi/entrypoint/default.py#L75-L148
