### ISSUE TITLE
Update database versions to Kodi v19 - Matrix

### ISSUE THREAD

**Issue by graybush** [jellyfin/jellyfin-kodi#59]
Currently the Kodi database's versions are in line with Kodi v17. 
https://github.com/jellyfin/jellyfin-kodi/blob/5944e47efafba0435fdbc745c4184de6c3b7f9fb/resources/lib/objects/obj_map.json#L1-L5
[Current Kodi database versions:](https://kodi.wiki/view/Databases#Database_Versions)
<table class="prettytable">
<tr>
<th> Kodi version </th>
<th> Date </th>
<th> MyVideos </th>
<th> MyMusic </th>
<th> Textures </th>
</tr>
<tr>
<td style="width:120px;"> v17 - Krypton
</td>
<td style="width:120px;"> February 2017
</td>
<td style="width:80px; text-align:center;"> 107
</td>
<td style="width:80px; text-align:center;"> 60
</td>
<td style="width:80px; text-align:center;"> 13
</td>
<tr>
<td style="width:120px;"> v19 - Matrix
</td>
<td style="width:120px;"> July 2019
</td>
<td style="width:80px; text-align:center;"> 116
</td>
<td style="width:80px; text-align:center;"> 72
</td>
<td style="width:80px; text-align:center;"> 13
</td>
</tr>
</table>
<p><br />
</p>

**Comment by oddstr13** [comment]
Ubuntu LTS (thus Mint) and Debian stable are still on Kodi 17

Kodi 18 is supposed to work.
I have not yet tried Kodi 19.

**Comment by graybush** [comment]
Does the project then target Ubuntu LTS? I only discovered this because I believe the current version of Kodi in RPM Fusion for Fedora 30 is 18.3.
Currently I use Kodi 18.3.

**Comment by oddstr13** [comment]
I'm personally running Mint (Ubuntu LTS), which means that is what I'm targeting.
There are patches merged that should make it work with 18.x.
I'd say we should aim to support whatever is in the debin stable (backport) and Ubuntu LTS arepositories and newer.

**Comment by mcarlton00** [comment]
I haven't seen any Kodi v19 in the wild yet.  All my machines I test against currently are either Arch (18.3) or LibreElec (18.2)

**Comment by jmeacoe** [comment]
Music will work as myMusic72 is the db used for Kodi 18.
Will need to look at the differences for myVideos.

**Comment by TrueTechy** [comment]
According to the Kodi [wiki](https://kodi.wiki/view/Databases#Database_Versions) the only difference between v18 and v19 is for the TV DB. To upgrade from 17 to 18 the Videos, Music, TV and EPG db would need to be worked on

**Comment by mcarlton00** [comment]
Using the existing library versions seems to work fine, given that we've all been running on Kodi 18 without issue for months and Kodi 19 support appears to be working fine currently.  So my guess is that these are generally less "breaking changes" and more "increased optional features" of some sort.

The downside of this is that the logs throw nasty errors since it's currently hardcoded to the Kodi 17 values.  It doesn't appear to be harmful, but it is annoying.  Given that the existing schema is still working fine, it seems as though we should be able to rework the map file to point towards the correct DB file for each Kodi version.  I'm hesitant about this because it means that the schema isn't actually correct for each version, but there isn't really a great way of handling that

**Comment by oddstr13** [comment]
Current database versions are
 - MyVideos 118
 - MyMusic 79
