### ISSUE TITLE
KODI Library shows different season information than jellyfin itself

### ISSUE THREAD

**Issue by eightsheep67** [jellyfin/jellyfin-kodi#602]
KODI Library shows different season information than jellyfin itself.

These are my episode files and jellyfin library
![1](https://user-images.githubusercontent.com/70835718/146646026-e7c67702-f121-485c-918d-e1ac4ee8835f.png)

and this is my kodi library
![2](https://user-images.githubusercontent.com/70835718/146646042-de0d3232-8912-4cf0-ac14-047801a9ef37.png)

I renamed those video files in order to match the NF episode order and I succeed to scrap all correct metadata. And Jellyfin displays fine.
Why Kodi addon cannot read the library correctly?

**Comment by mcarlton00** [comment]
I'm not entirely sure what I'm looking at here.  Your file structure doesn't match what we [generally recommend](https://jellyfin.org/docs/general/server/media/shows.html), but it is close.  I'm a little surprised having things labeled as `Part 01` instead of `Season 01` is working in the server at all, to be honest.  You have multiple nfo files for the same episode, and some of them seems like they should be completely ignored because the filenames don't match (`Part 01 - 0x01.nfo` vs `Part 01 - 0x1.nfo`).  And you're explicitly listing episodes as if they're a `Season 0` (the `0x` part of your filenames), which is commonly classified as Specials in a lot of cases.  So what's probably happening is that you're directly telling the server "This is Season 0, Episode 1".  The server is able to deal with that and display it based on the folder structure, but Kodi works entirely off metadata and is automatically sorting episodes based on that.  ie: Anything that's labeled as Season 0 is probably getting put into that Specials category.

**Comment by eightsheep67** [comment]
> I'm not entirely sure what I'm looking at here. Your file structure doesn't match what we [generally recommend](https://jellyfin.org/docs/general/server/media/shows.html), but it is close. I'm a little surprised having things labeled as `Part 01` instead of `Season 01` is working in the server at all, to be honest. You have multiple nfo files for the same episode, and some of them seems like they should be completely ignored because the filenames don't match (`Part 01 - 0x01.nfo` vs `Part 01 - 0x1.nfo`). And you're explicitly listing episodes as if they're a `Season 0` (the `0x` part of your filenames), which is commonly classified as Specials in a lot of cases. So what's probably happening is that you're directly telling the server "This is Season 0, Episode 1". The server is able to deal with that and display it based on the folder structure, but Kodi works entirely off metadata and is automatically sorting episodes based on that. ie: Anything that's labeled as Season 0 is probably getting put into that Specials category.

This is the only way I can manually choose the tmdb episode group order...
After last night testing, I think now I understand how kodi jellyfin plugin works.
Like you said Kodi doesn't read the folder structure. Now I use the Jellycon, Slow but correct.
