### ISSUE TITLE
No reconnect when server restarts

### ISSUE THREAD

**Issue by criena** [jellyfin/jellyfin-kodi#627]
**Describe the bug**

In case the Jellyfin server is restarted (e.g. due to a system upgrade), the plugin doesn't reconnect.

**To Reproduce**

1. Make sure Jellyfin server is up and running
2. Start Kodi and make sure the plugin connects to the Jellyfin server
3. Restart the Jellyfin server

**Expected behavior**

The plugin should try to reconnect whenever connectivity to the Jellyfin server is lost. Alternatively this could be a configurable setting.

**System (please complete the following information):**

 - OS: LibreELEC 10.0.2 (same with earlier versions)
 - Jellyfin Version: 10.7.7 (same with earlier versions)
 - Kodi Version: 19.4
 - Addon Version: 0.7.7

**Comment by mcarlton00** [comment]
If you're referring to websockets/remote control, then that's already been fixed in master, but hasn't been released yet.  If you're saying that local control/playback doesn't work after restarting the server, you likely have something unrelated broken in your setup.  As long as the server responds, the local control should always work.

**Comment by criena** [comment]
Yes, that's it. I just saw the pull request from November. Looking forward to the release! Thanks.
