### ISSUE TITLE
Rebase on Emby-next-gen v6

### ISSUE THREAD

**Issue by blackwind** [jellyfin/jellyfin-kodi#647]
Having recently migrated from Emby and the Emby-next-gen Kodi add-on, I'd like to point out something you guys may not even be aware of -- Emby-next-gen v6 is kind of amazing. It's everything I've ever wanted from a media server integration add-on, and I miss it dearly.

Here are some benefits of Emby-next-gen v6 as compared to v5 and Jellyfin for Kodi:

* Much quicker to sync, both in terms of initial sync and mirroring what was just changed on the server.
* Much quicker to start streaming.
* Much more reliable. In Emby-next-gen v5, I often had missing images, items I deleted lingered for no apparent reason, library changes often didn't populate until the add-on was restarted, library changes sometimes didn't populate at all until manually refreshing libraries, and so on and so forth. Emby-next-gen v6? No issues whatsoever. Jellyfin for Kodi? Back to the same old frustrations.
* Many more features. Delete from Kodi = delete on server is one I'm missing in particular, as it allows me to use Kodi add-ons like After Watch and Janitor again like the good ol' days.

Over there, development is going 100mph; here, 99% of the commits are string translations. Jellyfin users deserve a really great Kodi add-on too, and while I, of course, appreciate the unpaid volunteer hours of everyone here, the fact is, we're behind in a big way. I understand Jellyfin has diverged from Emby to some extent and the code won't be directly transferrable, but I strongly recommend investigating a rebase on Emby-next-gen v6 -- if not for the end-user benefits, then at least for the development benefit of not having to maintain the add-on for two different versions of Python.

**Comment by cvium** [comment]
I don't think you realise how much work that would be. It's not going to happen :)

**Comment by oddstr13** [comment]
I would like to point out that maintaining Python 2 (and Kodi 18) support is an explicit choice from our part.

Our current support strategy is full support for latest major Kodi release, and best-effort (not nececarily tested) support for previous release. Next release gains support when we think it starts to stabilize, probably around beta releases some time.

Python 2 support will *not* be dropped *before* Kodi 20 is fully released. After that, we'll see.


In my experience, playback starts within a few seconds.
Syncs can be a little slow to initiate on startup, but the scan itself is significantly faster than what it was when we inherited the code base.
I'm not sure of what's up with some people having to manually re-scan occationally.

The delete support is something that should work in theory, but in practice isn't maintained, because none of the current maintainers has any interest in using such a feature, even for testing purposes.
**It is good practice to not even give Jellyfin write accsess to the media directories!**
[If this is a feature you want, you should probably stick with Emby.](https://www.reddit.com/r/emby/comments/azxetx/emby_latest_release_deletes_entire_libraries/)


The fact that there are a lot of translation commits simply means translations are constantly being improved, and the reason there aren't that many other commits is because the plugin is in a reasonably stable state, not requiring many fixes. My garden, and gaming with my friends also both have higher priority than rewriting large chunks (possibly introducing bugs, causr Kodi addons are notoriously hard to write tests for) of this addon for minimal gains.
Improving sync speed and reliability would also require rewriting the server side plugin, and by your description above, it sounds like Emby has done that in their counterpart.


I honestly don't care if you use Emby over Jellyfin, as my motivation for contributing to the Jellyfin project relies 100%  on me wanting a good, *OpenSource* media server.
If other people find my work useful, that's a bonus.

**Comment by mcarlton00** [comment]
To give more context to this, what you're essentially asking is "throw away the last 3 years of work and thousands of lines of code you've written and start fresh from an unfamiliar codebase."  Not to mention all the changes that would have to happen _after_ copying their codebase to A: get it working with our server and B: unfuck some of their poor dev practices _again_.  It's not even remotely realistic, full stop.  If you have specific requests, feel free to open individual issues for them and we can talk about them in detail there.  If you have ideas of how to implement them, even better.  But if the suggestion is "just make it like/copy it from the other guys" then you're not going to get a good reaction.

Of what you listed, I can give you hints of what a likely cause is, but they're just guesses.

> Much quicker to sync, both in terms of initial sync and mirroring what was just changed on the server.

Especially during updates from the server, this requires changes in the server and/or the sync queue plugin.  We're somewhat limited on the client side.

> missing images

Disable http2 in kodi.  It appears to be somewhat inconsistent and cause issues with a lot of addons.

> library changes often didn't populate until the add-on was restarted

Your home screen doesn't update automatically.  It usually needs a reload skin called before things will display.

> library changes sometimes didn't populate at all until manually refreshing libraries

your network traffic was interrupted and caused the websocket connection to fail, should be fixed in the current release going forward

> Delete from Kodi = delete on server is one I'm missing in particular

This doesn't work because the two of us who primarily maintain this addon hate that feature and neither of us have been willing to look into it so far.
