### ISSUE TITLE
Errors when server URL lacks protocol

### ISSUE THREAD

**Issue by SenojLuap** [jellyfin/jellyfin-kodi#654]
**Describe the bug**
After installing and configuring the plugin, a prompt comes up that something went wrong (triggered either over time or when attempting to watch a video), and the video will not play.

**To Reproduce**
1. Install jellyfin plugin
2. Configure plugin as Add-On and add libraries
3. See error

**Logs**
[LogFiles](https://paste.kodi.tv/iveqezoxoz.kodi)

In case my jellyfin setup is relevant, here's the docker compose I used to run it on my NAS: https://paste.kodi.tv/vejujetore

**System (please complete the following information):**
 - OS: Hardkernel ODROID-N2Plus with CoreELEC
 - Jellyfin Version: 10.7.7
 - Kodi Version: 19.4
 - Addon Version: 0.7.8
 - Playback Mode: Add-On

**Additional context**
I previously had the plugin installed and connected to a different jellyfin server (different machine but same setup as the docker compose shared above), and that worked perfectly. I uninstalled the jellyfin plugin (selecting the option to delete all data) then reinstalled it to point to the new server (which is where the steps to reproduce come in).

**Comment by oddstr13** [comment]
You're missing http(s):// in your server URL.
Seems we aren't currently sanetizing that in this client…

**Comment by SenojLuap** [comment]
After updating the published server URL to include http:// it started behaving correctly.

I'd like to keep the ticket open to potentially get a better fix in for this

**Comment by the-lazy-fox** [comment]
Hello,
I've made a lot of test yesterday and didn't put http:// and I was able to connect,
Kodi on LibreElec.

**Comment by mcarlton00** [comment]
This issue is specifically when auto discovery and what the server is configured to provide to the client.  The server provides an address and we use it without any modifications.  If there's any sanitizing of this it should be done in the server instead of having to manually work around it individually in all of the clients.  The upcoming network manager rework in the server may already address this, but regardless I don't think we should be changing it client side.
