### ISSUE TITLE
Mixed content type shows in Movies

### ISSUE THREAD

**Issue by Sector14** [jellyfin/jellyfin-kodi#669]
**Describe the bug**
When using the web interface everything is nice and organised, Movies/TV Shows/Music/Music Videos as their respective content types and then as mixed content I have "Videos" and "Home Videos" available. The latter two are used for misc videos that don't fit anywhere else and our home videos.

When this is sync'd to kodi using the Jellyfin kodi add-on (not jellycon), the items marked as mixed content show up mixed in with movies in the Movies section.

**To Reproduce**
Add a library and mark it as Movie content. Then add a different library marked as "Mixed". This second libraries content ends up mixed in with Movies when using the kodi plugin, but is fine/separate in the web interface.

**Expected behavior**
I'd expect the Mixed content items to not appear in any of the specific content categories (Movies/TV Shows etc.) and either appear under the Kodi Videos section, or require you to browse via the add-on.

**System (please complete the following information):**
 - OS: Debian Bullseye
 - Jellyfin Version: 10.8.4
 - Kodi Version: 19.1
 - Addon Version: 0.7.8+py3
 - Playback Mode: Add-on

**Additional context**
I've also tried installing the Jellycon plugin. This keeps Movies/TV Shows/Photos showing just their respective content however the "Mixed conent" type for Videos and Home Videos do not show up at all anywhere in that plugin.

**Comment by Sector14** [comment]
Resolved the issue for now by not selecting the "Videos" library when adding libraries from jellyfin. Just added Movies, Music, Music Videos and TV Shows. I can find the misc Videos using the add-on dynamic menus. 

That said, it would be nice if there was a way to flag content on jellyfin with a type that would allow it show up under "Videos" in a folder browsing structure and likewise for Photos to show up under Pictures. I assume how kodi handles things is why the plugin doesn't support this. Is it likely a future feature or just not possible with the current kodi plugin api?

**Comment by mcarlton00** [comment]
So this is complicated in a lot of ways, and honestly not likely to change.  I'll try to hit as many points as I can think of so it's not seen as just me being dismissive.

Kodi only has one videos database and it puts everything in there together, as their respective types in separate tables (see below).  And everything in the Jellyfin server has a media type, obviously.  When using a Mixed library, you're essentially saying "combine my movies and tv shows together" (which frankly doesn't work well and is no end of headaches for those of us supporting people who choose to use it).  So in this case, all of your home videos are being categorized by jellyfin as a movie.  When the metadata is synced from Jellyfin to Kodi, it uses the types that the server has as a reference for which media type it should be matched to in Kodi's database.  So yes, it will always get mixed together.  The same thing happens when you have multiple movie or tv shows libraries and sync them all; they get merged into just the library types that Kodi has defined: Movies, TV Shows, Music, or Music Videos, with no library boundaries.  There's really not much we can do about that.

```
% sqlite3 .kodi/userdata/Database/MyVideos119.db
SQLite version 3.39.1 2022-07-13 19:41:41
Enter ".help" for usage hints.
sqlite> .tables
actor                   movie_view              studio_link
actor_link              movielinktvshow         tag
art                     musicvideo              tag_link
bookmark                musicvideo_view         tvshow
country                 path                    tvshow_view
country_link            rating                  tvshowcounts
director_link           season_view             tvshowlinkpath
episode                 seasons                 tvshowlinkpath_minview
episode_view            sets                    uniqueid
files                   settings                version
genre                   stacktimes              writer_link
genre_link              streamdetails
movie                   studio
```
I'm not sure how Kodi's generic "videos" section works, but as you can see above there's no table for it.  As such, I have no idea how to populate that section with items from within a mixed library.  Not to mention, this would absolutely be a drastic change from the current behavior that I'm sure a lot of people rely on.

> Is it likely a future feature or just not possible with the current kodi plugin api?

As if the above wasn't complicated enough for you, this is another area.  There is no plugin api to add items to Kodi's database.  It's not supported, full stop.  This addon functions by blatantly ignoring what Kodi _wants_ to do, and writing directly to the database file on the disk.  The column names in each of those tables above are less than descriptive, and the [documentation](https://kodi.wiki/view/Databases/MyVideos) for how those databases are meant to be populated is rather lacking.  This is because modifying it is supposed to be a big no no, and it's for internal Kodi use only.  So to answer your question, it's _in theory_ possible to change the behavior and provide some limited support for other types/views.  It will require figuring out what data Kodi wants where, populating the relevant table(s), linking them where appropriate, etc.  Basically, reverse engineering how vanilla Kodi handles it.  It's .... a lot.

> JellyCon

You're correct, JellyCon doesn't currently support mixed libraries.  There's an open issue where I've gone into some of the challenges about it [here](https://github.com/jellyfin/jellycon/issues/46).  I have some strong opinions about mixed libraries in general, but the TLDR is that they're awful in basically every way imaginable.

**Comment by Sector14** [comment]
Thanks for the detailed response.

I reworked how I use the pluging earlier, so now I only have it sync/import the fully supported types, Movies, Tv Shows, Music, Music Videos. I've then set Photos and Home Video libraries both under the "photo" type and "Videos" is under "Mixed" (with all scrapers disabled except image extract) although in hindsight also putting that in as a "Photos" type may have made sense.

That gets the 4 main libraries working nicely in kodi via the main menu, then the rest (Videos/Photos and Home Videos) are just one menu item deeper under "favourites". Not perfect due to the slight loading delay as it queries the server each time, but, perfectly usable. 

If anyone else uses this setup and at the risk of stating the obvious, just remember to use the Videos Add-on when adding the favourite for videos/home videos libraries and use the Photos add-on for photos. Otherwise the photos show up but can't actually be viewed.

**Comment by mcarlton00** [comment]
For the reasons mentioned above, I don't think the functionality can change here in any reasonable form.  It's a pretty big rabbit hole and would be a major change, probably breaking some folks' current setups.

However, I do have Mixed Libraries working in JellyCon now, so you can use that instead, or in addition to.  It should be possible to get those "dynamic" menus to load faster here (because yes, they are horribly slow), but as most of the usability of this addon is syncing that data into the local database instead, there hasn't been a ton of work into that yet.
