### ISSUE TITLE
Kodi crashes after playing second video through Jellyfin

### ISSUE THREAD

**Issue by dukenukemx** [jellyfin/jellyfin-kodi#676]
**Describe the bug**
When I play a video for the second time through the Jellyfin plugin in Kodi, it will crash and close.  

**To Reproduce**
Play a video and stop it or let the video run its course.  Do it again and it won't play and Kodi crashes.  

**System (please complete the following information):**
 - OS: Linux Mint 21
 - Jellyfin Version: 10.8.4
 - Kodi Version: 20 but I've also tested this on 19
 - Addon Version: angelblue05-0.7.8+py3
 - Playback Mode: Native

**Additional context**
I've read on reddit and other sources about this problem and I think it's python related, but those were relatively old posts so I'm wondering if there's a fix?  
**LOG**
[kodi_log.txt](https://github.com/jellyfin/jellyfin-kodi/files/9522429/kodi_log.txt)

**Comment by whyiseveryfuckingnameisalreadyused** [comment]
I think it's the same as my issue [603] (https://github.com/jellyfin/jellyfin-kodi/issues/603) seems like the new mint ships the borked python versions, it's fixed for a while now in upstream.

**Comment by dukenukemx** [comment]
Yea it's been fixed with an update.  I guess one of the Python updates fixed it?

**Comment by mcarlton00** [comment]
This was likely an upstream issue.  For a while I was experiencing crashes when trying to do nearly anything with the addon, and it's fixed itself since then.  I believe it was [this issue](https://github.com/python/cpython/issues/90619).  Since it appears to be fixed and it out of our hands, I'm gonna go ahead and close this one.  Thanks for confirming @dukenukemx
