### ISSUE TITLE
Feature request: throttle library syncs

### ISSUE THREAD

**Issue by unikitty37** [jellyfin/jellyfin-kodi#759]
**Describe the bug**
I am using Jellyfin on a Vero 4K+. It is not good with heat, and syncing my TV and movie libraries usually causes it to overheat and hang. The power then needs to be disconnected and the unit allowed to cool, before reconnecting the power and letting the sync continue.

There are two additional issues that don't help: one is that, after rebooting, Kodi seems to sit for ages before deciding it should try connecting to Jellyfin. Is there a way to get it to do it sooner?

The second issue is that, after an overheat and crash, when jellyfin-kodi asks if it should resume the previous sync, it often fails to resume and just starts over — so it can never reach the end, because it always overheats after syncing things it has _already synced_.

It would be very useful if the plugin allowed users to (optionally!) slow the sync rate, rather than having it try to go as fast as it can. A library sync that pauses for one second after each entry, takes ten hours, but completes successfully and allows Kodi to be used throughout, is better than a library sync that _would_ have taken 30 minutes if only it didn't keep overheating the box it's running on, causing it to crash :)

**System (please complete the following information):**
 - OS: OSMC 2023.07-1, with kernel 4.9.269-32-osm
 - Jellyfin Version: 10.18.10
 - Kodi Version: 20.2
 - Addon Version: 0.7.10+py3
 - Playback Mode: Add-On

**Comment by YoBii** [comment]
Good suggestion.

Are you sure though your 4K+ is 'just' overheating? Because I noticed a stalling behavior during syncs (but also at other times) not even using jellyfin but PKC with my 4K+.
I observed the system runs out of memory which will cause **kswapd0** to run wild and hog the cpu until the system comes to a halt. I think it's related to heavier skins or rather widgets (or maybe artwork caching) and OSMCs memory management.
Maybe this is happening here as well..?

**Comment by unikitty37** [comment]
Hmm — that's possible. I've since replaced it with a Vero V, which has twice as much RAM and hasn't been affected so far.

After completing the sync and letting things cool down, I did have a similar hang when paging through the library. Since I'd cleared the artwork cache, it was all getting re-cached, so artwork caching looks like a possibility there.

It would probably still help to be able to slow down the sync, but that's probably a fairly low priority…

**Comment by mcarlton00** [comment]
Trust me when I say it's not trying to go as fast as it can.  After a round of optimizing the sync process in the past, we've had to slow it down another 10% or so iirc so low power devices would function properly.  I do my low power testing on a Pi 3 (which is an absolute potato at this point) and it has no issues, so if the Vero is having trouble that sounds more like it's a device engineering failure that we're not really going to be able to do much about outside of telling you to put a fan on it instead of relying on passive cooling in the enclosed case.  There's already _some_ sync tuning in the settings, but I'm not sure which way you want to adjust things, I'd guess less threads.  Settings -> Sync -> Paging.  Probably lower the resolution of artwork as well, just to make it work a little less hard.

**Comment by oddstr13** [comment]
Do these addon settings under sync not help?
Try setting download threads to 1 for example
![image](https://github.com/jellyfin/jellyfin-kodi/assets/638706/ee328680-09e0-44c3-9426-589ea3f30621)

**Comment by unikitty37** [comment]
Thanks — I hadn't noticed those settings.

I suspect that the cooling on that particular 4K+ was having problems, as other users don't seem to be having the same problem. Either way, it looks like the plugin's not to blame here, so I'll close this.
