### ISSUE TITLE
Kodi doesn't see JF Libraries. 

### ISSUE THREAD

**Issue by LentulisBatiatus** [jellyfin/jellyfin-kodi#836]
Trying to setup a Kodi client for a JF server on a machine that used to be the JF server. Installed Kodi and the JF Repo and then the JF addon. Kodi-JF finds the local server and accesses the user properly. When trying to Add Libraries the list does not populate.

Both the server machine and another Kodi client machine have no issues populating the JF library in Kodi with the addon. Everything works as it should.

All systems running Windows 10. All on a LAN.  All setup in Native mode. Tried multiple attempts on the troublesome machine and always get the same result with no indication as to what is going wrong. This machine had no issues using the JF addon in this manner when this machine was the JF host server previously. It can also use the JP desktop app and web browser with no issues and sees the server machine and all drives/files.

Unsure if this is the correct place to post this or what other info may be required.

**Comment by oddstr13** [comment]
You're not providing any of the requested information from the issue template, and as such this issue contains no actionable information.

**Comment by jordan-huitema** [comment]
Im getting the exact same issue on my system too. 

Reverting back to 7.12+py3 fixed the issue completely.

Im running a ubuntu 20.04 lxc container with the latest kodi release and 1.0 addon version.

2 days ago i noticed new episodes and movies being synced worked fine but the thumbnails weren't showing, checked jellyfin and everythings fine.

Tired to fix the issue today by doing a db reset and re adding all my libraries, this causes jellyfin addon to add 1 movie and then get stuck.

If i change the sync threads or download limit i get a sync error instead of a 'soft lock' when trying to sync so maybe its related?

About to go to bed so ill try get some logs and make a proper report after work tomorrow.

**Comment by Necronar** [comment]
> Im getting the exact same issue on my system too.
> 
> Reverting back to 7.12+py3 fixed the issue completely.
> 
> Im running a ubuntu 20.04 lxc container with the latest kodi release and 1.0 addon version.
> 
> 2 days ago i noticed new episodes and movies being synced worked fine but the thumbnails weren't showing, checked jellyfin and everythings fine.
> 
> Tired to fix the issue today by doing a db reset and re adding all my libraries, this causes jellyfin addon to add 1 movie and then get stuck.
> 
> If i change the sync threads or download limit i get a sync error instead of a 'soft lock' when trying to sync so maybe its related?
> 
> About to go to bed so ill try get some logs and make a proper report after work tomorrow.

You might be experiencing a different problem from OP. They're describing a first-time setup.

However, I'm having the same issue as you, as my Kodi just upgraded to 1.0 a couple of days ago, and I haven't been able to sync anything since. Just like you, it does 1 movie and get stuck. I can't playback either.

The issue seems to be due to 1.0, which was released 3 days ago, rather than OP's issue which was posted 2 weeks ago.

**Comment by oddstr13** [comment]
@Necronar @jordan-huitema sounds like you guys are having a completely different issue.

OP hasn't provided any information I can work with on their issue, closing.
