### ISSUE TITLE
Auto generate .strm for Kodi

### ISSUE THREAD

**Issue by alazabe** [jellyfin/jellyfin-kodi#901]
Hi , 

I would like to see the addon auto generate. .Strm files to use with kodi just like Google drive and netflix addon do ! 

And that will make it easy to mange all extra fanart  trailers and metadata to be controlled from my PC ! 
And that will be a lot helpful for people with large library ! 

And I want kodi to treat it as if it was a local !

**Comment by mcarlton00** [comment]
> And that will be a lot helpful for people with large library !

Minor correction.  This will _drastically_ slow down how long it takes to import the jellyfin library.  Like somewhere between 3x and 6x as long.  I've spent quite a bit of time looking into alternative methods of importing the library and doing benchmarking, and options aren't good.

Some other factors with changing to strm files:
* It will complicate the transcoding support and likely slow the playback processing down because there's now more links in the chain.
* This will also increase the storage requirements on the client, which quickly gets out of hand and basically eliminates the possibility for running on low power android tv boxes.  Also potential to introduce performance issues as you start dumping thousands of files onto the filesystem that the OS has to sort through.
* Using Kodi metadata providers or fanart providers won't push that metadata back into the server, so now all of that is exclusive to this one Kodi instance and not any other clients.
* Just a _lot_ of work refactoring things.
* "I want kodi to treat it as if it was a local!" - this completely defeats the purpose of having a centralized server to manage things.  Honestly, if that's what you want, it's way, _way_ easier to just use your media local and use trakt to sync your watched status.

**Comment by oddstr13** [comment]
This is something we've discussed in the past, and the conclusion is that it isn't viable.
If this is something you *really* want, the best way to implement it would likely be as a Jellyfin server plugin that exposes the libraries as a directory structure over http, where strm files would be generated and served on demand.

Closing as out of scope for this project.
